services:
  nextjs:
    user: "1000:1000"
    build:
      context: .
      args:
        NODE_ENV: development
        DATABASE_URL: "mysql://root:rootpass@db:3306/dungeonguide-local"
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
    - .:/app
    - node_modules:/app/node_modules

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dungeonguide-local
      MYSQL_USER: nextuser
      MYSQL_PASSWORD: nextpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
  node_modules: