import type { Metadata } from "next";
import Header from '@/components/header';
import Footer from '@/components/footer';
import { AuthProvider } from '@/context/AuthContext';
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Header/>
          <main className="main-content">
            {children}
          </main>
          <Footer/>
        </AuthProvider>
      </body>
    </html>
  );
}
